    version: '3.7'
    services:
        postgres:
            image: postgres:9.6
            environment:
                - POSTGRES_USER=airflow
                - POSTGRES_PASSWORD=airflow
                - POSTGRES_DB=

            ports:
                - "5432:5432"
            logging:
                options:
                    max-size: 10m
                    max-file: "3"

        webserver:
            image: puckel/docker-airflow:1.10.9
            restart: always
            depends_on:
                - postgres
            environment:
                - LOAD_EX=n
                - EXECUTOR=Local
                - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
                - AIRFLOW__WEBSERVER__WORKERS=1
            logging:
                options:
                    max-size: 10m
                    max-file: "3"
            volumes:
                - ${RAINBOW_HOME}:/usr/local/airflow/dags
                - ${HOME}/.kube:/usr/local/airflow/.kube
            ports:
                - "8080:8080"
            command: webserver
            healthcheck:
                test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
                interval: 30s
                timeout: 30s
                retries: 3
